### ISSUE TITLE
Is it actually necessary to build a batch-style API?

### ISSUE THREAD

**Issue by my2iu** [FrankYFTang/proposal-intl-segmenter-v2#2]
I don't know why the Skia people keep insisting on a batch API for WASM. You can't call directly into JavaScript from WASM anyway, so the design of a JS API doesn't have any effect on the number of JS <-> WASM calls. The Skia people are the ones who write the code that marshals data from WASM to JS (for example, the raw utf-8/16/32 data stored in WASM memory would need to be converted to JS strings), so Skia can implement whatever batching they want to get the performance they need. As far as I know, whether the JS part of the API is batched or not doesn't matter.

**Comment by FrankYFTang** [comment]
You make a good point. I discussed with Skia team after I saw your feedback and we decide to listen to your feedback and drop that part from the proposal.
