### ISSUE TITLE
Segmenter should have a generic option where no locale/language needs to be specified

### ISSUE THREAD

**Issue by my2iu** [FrankYFTang/proposal-intl-segmenter-v2#3]
Needing to specify set locales is very restrictive. This isn't the old days of packaged software where software is sold in separate English, Spanish, and Chinese versions, etc. On the web, everything is more fluid and diverse, and that's a good thing. I should be able to enter my name in Chinese on an English web game, and it should still format properly. I should be able to enter some Hindi text on a Japanese website for graphing things, and it should still format properly.

There should be a generic option where the segmenter will automatically break up text into different scripts and apply reasonable segmentation rules to the different scripts.

**Comment by FrankYFTang** [comment]
Please read " locale-sensitive boundary suppression specifications " and "
tailored grapheme clusters" in https://unicode.org/reports/tr29/ to understand why the API require locale parameter. You can enter [] as locale and the API should still be able to work for the case you describe, but won't work for some more advanced requirement.

**Comment by my2iu** [comment]
Awesome. I know having a locale helps with certain situations but I just wanted to make sure the proposal had an option for still doing something reasonable if no locale is provided or the wrong locale is provided.

**Comment by FrankYFTang** [comment]
Give you a concrete example of why locale is needed for Segmenter- take a look at https://unicode-org.atlassian.net/browse/ICU-21854
some language need specific rule for those issue only inside that language. There are rule which most language follow, but there are cases that the usage in two language conflict against each other and it will be impossible to have one to make both usage happy.

**Comment by my2iu** [comment]
Sure, that particular example is somewhat ambiguous because for normal French speakers, I don’t think it makes a big difference either way. But I agree that in many cases, having a locale is useful. 

I just think that 99% of the JS code that uses the API is going to be some copy-pasted code from StackOverflow or some NPM library that uses “en” as the locale or no locale at all. So it’s important that the spec says that the API implementations should still *try* to do something reasonable in those situations.

**Comment by FrankYFTang** [comment]
> it’s important that the spec says that the API implementations should still _try_ to do something reasonable in those situations.

That is covered by https://unicode.org/reports/tr29/ and http://unicode.org/reports/tr14/ which ECMA402 and it's proposal defer the detail to.
