### ISSUE TITLE
Does JS have an API for finding surrogate pairs in a String?

### ISSUE THREAD

**Issue by my2iu** [FrankYFTang/proposal-intl-segmenter-v2#4]
The suggested segmentation API seems to walk through codepoints of a string and reports different things for different surrogates etc. But does JavaScript actually have an API yet for testing whether a character in a string is a high/low surrogate or not? Is there a way to determine where the different codepoints are in a String? I know I'm not always up-to-date on the latest spec changes, but every time I look up MDN, I'm not seeing any API for that, and such an API is needed to properly use the suggested segmentation API.

**Comment by FrankYFTang** [comment]
You asked a good question but that belong to https://github.com/tc39/ecma402/issues not here.
