### ISSUE TITLE
Feature detection

### ISSUE THREAD

**Issue by mdebbar** [FrankYFTang/proposal-intl-segmenter-v2#5]
This API will take time to propagate to all browsers. As web developers, we need a way to detect whether the API is available or not.

I tried this on Chrome, Firefox and Safari:
```js
s = new Intl.Segmenter("en", {granularity: "line"})
```
and they all throw an error because "line" isn't a supported granularity.

So a developer could use a function like this to check for "line" support:
```js
function isLineSegmenterSupported() {
  try {
    new Intl.Segmenter("en", {granularity: "line"})
    return true;
  } catch(_) {
    return false;
  }
}
```
Is this an okay way to do feature detection for this new API?

**Comment by FrankYFTang** [comment]
I believe that is the intended way to do so.
